### ISSUE TITLE
Share item on facebook?

### ISSUE THREAD

**Issue by masonshuler** [masonshuler/CloudApp#14]
https://developers.facebook.com/docs/plugins/share-button

**Comment by mrtuckman** [comment]
Sounds like a great idea to me that would enhance our overall project with a robust new feature!

**Comment by jtkuhn** [comment]
![image](https://user-images.githubusercontent.com/11926709/38880933-e0c62df2-4234-11e8-9b91-2b9edb4dfcc9.png)
