### ISSUE TITLE
SQL User table not being deleted during .sql execution. 

### ISSUE THREAD

**Issue by masonshuler** [masonshuler/CloudApp#16]
[Warning, Error code 1,217, SQLState 23000] Cannot delete or update a parent row: a foreign key constraint fails

[Exception, Error code 1,217, SQLState 23000] Cannot delete or update a parent row: a foreign key constraint fails
Line 1, column 1

[Warning, Error code 1,050, SQLState 42S01] Table 'user' already exists

**Comment by mrtuckman** [comment]
I'm not sure why the first line "DROP TABLE IF EXISTS UserPhoto, ItemPhoto, Item, User;" does not handle this. We can talk about it more in class.

**Comment by mrtuckman** [comment]
Additionally I found this in the documentation:
DROP TABLE cannot be used to drop a table that is referenced by a FOREIGN KEY constraint. The referencing FOREIGN KEY constraint or the referencing table must first be dropped. If both the referencing table and the table that holds the primary key are being dropped in the same DROP TABLE statement, the referencing table must be listed first.

**Comment by masonshuler** [comment]
fixed by deleting database and renaming it. Something to do with the old User table
