### ISSUE TITLE
account password not working after clean/build

### ISSUE THREAD

**Issue by masonshuler** [masonshuler/CloudApp#38]

**Comment by mrtuckman** [comment]
![image](https://user-images.githubusercontent.com/15697211/39265355-0e54242a-4895-11e8-852b-3c8a438d38da.png)

**Comment by masonshuler** [comment]
Are you trying to use the matt_tuckman account? are you emails the same for the admin accounts?

**Comment by mrtuckman** [comment]
Email are different for every account, but all the passwords are the same and as you can see the hashes are not the same. I am not using the first account, that was the one that I was testing the password changing on.

**Comment by masonshuler** [comment]
The hashs should not be the same (for different emails) because they are salted. Maybe try updating the database?

**Comment by masonshuler** [comment]
If you take the SHA256 of the (password+email) like https://passwordsgenerator.net/sha256-hash-generator/ with the string Password22#test@gmail.com

**Comment by mrtuckman** [comment]
Oh right forgot about that

**Comment by masonshuler** [comment]
okay. I got it. The hash is being stored in binary as a string. The only problem is that mysql treats strings very weird on the mac os.

I will solve by storing the HEXdigest of the hash instead of the raw binary

**Comment by mrtuckman** [comment]
Awesome, let me know when you push it and I will test it on Mac to make sure it worked!
