### ISSUE TITLE
Tidy Up Index

### ISSUE THREAD

**Issue by mrtuckman** [masonshuler/CloudApp#40]
Currently the twitter feed is very short and the images in the image slider are not correctly resized. Additionally the background color is the default which I believe we wanted to change to the goodwill gray.

**Comment by masonshuler** [comment]
Has this been closed?

**Comment by mrtuckman** [comment]
The commit "Tweeked twitter timeline to be max width and match sliders height" partially fixed this. I will work on it tomorrow also.

**Comment by shuvesta** [comment]
what goodwill grey are you talking about? index is for the most part fixed.
https://www.w3schools.com/colors/colors_picker.asp
if you can get the html color code for the grey off this website we can change it super easily

**Comment by mrtuckman** [comment]
Finally fixed!
