### ISSUE TITLE
Create index

### ISSUE THREAD

**Issue by masonshuler** [masonshuler/CloudApp#6]

**Comment by masonshuler** [comment]
image1:
Goodwill finds to dye for
http://www.goodwill.org/wp-content/uploads/2018/03/vestido-300.jpg
http://www.goodwill.org/blog/shop/goodwill-finds-to-dye-for/

image2:
3 Creative Ways to Display Photos in Your Home
http://www.goodwill.org/wp-content/uploads/2018/03/quadro-300-300x150.jpg
http://www.goodwill.org/blog/shop/3-creative-ways-to-display-photos-in-your-home/

**Comment by jtkuhn** [comment]
image3:
Offline ways to donate to a local Goodwill:
https://2q3p9f1gkla37u7y226mrtt1-wpengine.netdna-ssl.com/wp-content/uploads/2015/08/Donation-Header.jpg
https://goodwillsp.org/donate/

image4:
Tips to save money:
https://www.frugalchiclife.com/wp-content/uploads/2017/08/31-FrugalLivingto-table-2.png
https://www.frugalchiclife.com/31-frugal-living-hacks-will-save-thousands/

**Comment by mrtuckman** [comment]
image 5:
http://www.goodwillduluth.org/clothing-donations-needed-at-goodwill-duluth/
https://goodwillduluth.files.wordpress.com/2012/10/sam-best_web.jpg

image 6:
https://www.yourgoodwill.org/images/store_images/Langhorne.jpg

**Comment by masonshuler** [comment]
<a class="twitter-timeline" href="https://twitter.com/GoodwillIntl?ref_src=twsrc%5Etfw">Tweets by Goodwill Industries</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

**Comment by masonshuler** [comment]
old issue. new issue is #40
