### ISSUE TITLE
Create Powerpoint Due Thursday April 5th

### ISSUE THREAD

**Issue by masonshuler** [masonshuler/CloudApp#7]
[Open this with your vt email](https://docs.google.com/presentation/d/13hdr_1cMe3EKSQjPOtLyCOenq9kxqsZaFqEmdzlFRjs/edit?usp=sharing)

Prepare your team's progress presentation in such a way that your team can complete the presentation in 7 minutes. Time your presentation and make sure that you do not exceed the time limit.

Name your presentation file as CS3754 Team N.pptx where N is your team number. You can use any presentation creation software, but you must export your presentation in the .pptx (PowerPoint) format.

Each Project Team is required to email the team's presentation slides in .pptx format at least 30 minutes before the class starts to Dr. Balci at balci@vt.edu.

Dr. Balci will download the presentations to his laptop and every team will use his laptop in making their presentation.

**Comment by masonshuler** [comment]
Can someone post an example powerpoint someone used last year?

**Comment by jtkuhn** [comment]
I only know one person who's taken the class before and he says he doesn't have their presentation. Can anybody else find one?
